// Auto-generated by scripts/generate-content.ts
// Do not edit manually - edit YAML files in /content instead

import { ContentBundle } from './types';

export const contentBundle: ContentBundle = {
  "vocab": {
    "version": "HPMA-Vocab-1.0",
    "enums": {
      "structure": [
        "SOLO",
        "DUET",
        "TRIO",
        "CHORD",
        "CHORUS",
        "MIST",
        "FAULTED"
      ],
      "duet_mode": [
        "TWIN_HELIX",
        "LEANING_HELIX",
        "KEYSTONE_LENS",
        "SIGNATURE_ACCENT",
        "PURELINE"
      ],
      "trio_mode": [
        "TRI_HELIX",
        "KEYSTONE_PRISM",
        "KEYSTONE_ORBIT",
        "TRIAD_STACK"
      ],
      "polyphonic_mode": [
        "CHORD_TOP4",
        "CHORD_TOP_HEAVY",
        "CHORUS_DISTRIBUTED",
        "CHORUS_CONTEXT_SPLIT"
      ]
    },
    "roles": {
      "anchor": "Anchor",
      "lens": "Lens",
      "accent": "Accent",
      "shadow": "Shadow",
      "keystone": "Keystone",
      "voice": "Voice"
    },
    "structure_labels": {
      "SOLO": "Solo",
      "DUET": "Duet",
      "TRIO": "Trio",
      "CHORD": "Chord",
      "CHORUS": "Chorus",
      "MIST": "Mist",
      "FAULTED": "Faulted"
    },
    "mode_labels": {
      "TWIN_HELIX": "Twin-Helix",
      "LEANING_HELIX": "Leaning Helix",
      "KEYSTONE_LENS": "Keystone & Lens",
      "SIGNATURE_ACCENT": "Signature & Accent",
      "PURELINE": "Pureline",
      "TRI_HELIX": "Tri-Helix",
      "KEYSTONE_PRISM": "Keystone Prism",
      "KEYSTONE_ORBIT": "Keystone Orbit",
      "TRIAD_STACK": "Triad Stack",
      "CHORD_TOP4": "Chord (Top-4)",
      "CHORD_TOP_HEAVY": "Chord (Top-Heavy)",
      "CHORUS_DISTRIBUTED": "Chorus (Distributed)",
      "CHORUS_CONTEXT_SPLIT": "Chorus (Context-Split)"
    },
    "print_rules": {
      "minimal_label": "{structure}: {identity} — {mode}",
      "full_label": "{structure}: {identity} — {mode} | Anchor={anchor} p1={p1}",
      "show_math": true
    }
  },
  "identities": {
    "version": "HPMA-Identities-1.0",
    "primaries": {
      "EXPLORER": {
        "name": "Explorer",
        "tagline": "Curiosity in motion. Seeks novel terrain.",
        "core_drive": "Autonomy + discovery",
        "icon": "🧭"
      },
      "PHILOSOPHER": {
        "name": "Philosopher",
        "tagline": "Meaning over noise. Depth over breadth.",
        "core_drive": "Purpose + coherence",
        "icon": "💭"
      },
      "ORGANIZER": {
        "name": "Organizer",
        "tagline": "Systems that work. Progress you can measure.",
        "core_drive": "Mastery + structure",
        "icon": "📐"
      },
      "CONNECTOR": {
        "name": "Connector",
        "tagline": "Bridges over walls. Belonging over isolation.",
        "core_drive": "Belonging + care",
        "icon": "🤝"
      },
      "PROTECTOR": {
        "name": "Protector",
        "tagline": "Safety first. Vigilance as love.",
        "core_drive": "Security + stability",
        "icon": "🛡️"
      },
      "PERFORMER": {
        "name": "Performer",
        "tagline": "Energy in the room. Play meets presence.",
        "core_drive": "Status + expression",
        "icon": "🎭"
      }
    },
    "dyads": {
      "SEEKER_SAGE": {
        "pair": [
          "EXPLORER",
          "PHILOSOPHER"
        ],
        "name": "Seeker-Sage",
        "tagline": "Discovery plus meaning. Curiosity with a compass."
      },
      "VISIONARY_BUILDER": {
        "pair": [
          "EXPLORER",
          "ORGANIZER"
        ],
        "name": "Visionary Builder",
        "tagline": "Ideas that ship. Exploration meets execution."
      },
      "WAYFINDER_DIPLOMAT": {
        "pair": [
          "EXPLORER",
          "CONNECTOR"
        ],
        "name": "Wayfinder Diplomat",
        "tagline": "New paths, new friends. Adventure as connection."
      },
      "SENTINEL_SCOUT": {
        "pair": [
          "EXPLORER",
          "PROTECTOR"
        ],
        "name": "Sentinel Scout",
        "tagline": "Careful curiosity. Exploration with eyes open."
      },
      "SPOTLIGHT_PIONEER": {
        "pair": [
          "EXPLORER",
          "PERFORMER"
        ],
        "name": "Spotlight Pioneer",
        "tagline": "First on stage, first on the trail. Bold and visible."
      },
      "SYSTEMS_THEORIST": {
        "pair": [
          "PHILOSOPHER",
          "ORGANIZER"
        ],
        "name": "Systems Theorist",
        "tagline": "Models that work. Theory meets practice."
      },
      "BRIDGE_SCHOLAR": {
        "pair": [
          "PHILOSOPHER",
          "CONNECTOR"
        ],
        "name": "Bridge Scholar",
        "tagline": "Depth plus warmth. Ideas as bridges."
      },
      "VIGILANT_STOIC": {
        "pair": [
          "PHILOSOPHER",
          "PROTECTOR"
        ],
        "name": "Vigilant Stoic",
        "tagline": "Prepared wisdom. Meaning under pressure."
      },
      "PUBLIC_INTELLECTUAL": {
        "pair": [
          "PHILOSOPHER",
          "PERFORMER"
        ],
        "name": "Public Intellectual",
        "tagline": "Ideas on stage. Thought leadership."
      },
      "COMMUNITY_OPERATOR": {
        "pair": [
          "ORGANIZER",
          "CONNECTOR"
        ],
        "name": "Community Operator",
        "tagline": "Systems for people. Structure that serves."
      },
      "RISK_STEWARD": {
        "pair": [
          "ORGANIZER",
          "PROTECTOR"
        ],
        "name": "Risk Steward",
        "tagline": "Managed uncertainty. Plans with backup plans."
      },
      "SHOWRUNNER_EXECUTIVE": {
        "pair": [
          "ORGANIZER",
          "PERFORMER"
        ],
        "name": "Showrunner Executive",
        "tagline": "Productions that deliver. Leadership with flair."
      },
      "GUARDIAN_CARETAKER": {
        "pair": [
          "CONNECTOR",
          "PROTECTOR"
        ],
        "name": "Guardian Caretaker",
        "tagline": "Safety through belonging. Protection as love."
      },
      "CHARISMATIC_HOST": {
        "pair": [
          "CONNECTOR",
          "PERFORMER"
        ],
        "name": "Charismatic Host",
        "tagline": "Everyone belongs. Energy that includes."
      },
      "WATCHFUL_CHAMPION": {
        "pair": [
          "PROTECTOR",
          "PERFORMER"
        ],
        "name": "Watchful Champion",
        "tagline": "Visible strength. Protection with presence."
      }
    },
    "fallback_template": "{A}–{B} Hybrid"
  },
  "modes": {
    "version": "HPMA-Modes-1.0",
    "duet_modes": {
      "TWIN_HELIX": {
        "name": "Twin-Helix",
        "ratio": "~50/50",
        "description": "Both voices are equally active. Context determines which leads at any moment.",
        "adds": {
          "strengths": [
            "Context-switching: you can run two engines without collapsing into one.",
            "Versatility: different situations call different voices forward naturally.",
            "Integration potential: when both align, you have unusual depth."
          ],
          "watchouts": [
            "Oscillation risk: swapping engines mid-decision can look like indecision.",
            "Identity confusion: 'which one am I really?' is a common internal question.",
            "Energy drain: maintaining two active modes requires more cognitive bandwidth."
          ],
          "prescriptions": [
            "Use explicit switching rules (e.g., 'morning is anchor time, evening is lens time').",
            "Name which voice is driving before big decisions.",
            "Create rituals that honor both voices regularly."
          ]
        }
      },
      "LEANING_HELIX": {
        "name": "Leaning Helix",
        "ratio": "~60/40",
        "description": "One voice leads slightly, but the other remains a strong co-driver.",
        "adds": {
          "strengths": [
            "Slight clarity: one voice has a gentle home-court advantage.",
            "Dynamic balance: still flexible enough to switch without strain.",
            "Reduced identity friction compared to pure Twin-Helix."
          ],
          "watchouts": [
            "Drift risk: the 60% voice may slowly absorb the 40% over time.",
            "Lens suppression: the secondary voice may feel perpetually 'almost' expressed."
          ],
          "prescriptions": [
            "Consciously activate the secondary voice weekly.",
            "Notice when you're defaulting and ask if the other voice would serve better."
          ]
        }
      },
      "KEYSTONE_LENS": {
        "name": "Keystone & Lens",
        "ratio": "~75/25",
        "description": "One clear keystone engine, with a consistent lens coloring expression.",
        "adds": {
          "strengths": [
            "Clarity: you know what drives you; decisions are faster.",
            "Consistency: others can predict your patterns.",
            "Lens depth: the 25% adds nuance without confusion."
          ],
          "watchouts": [
            "Lens neglect: the secondary voice may atrophy if never given airtime.",
            "Rigidity: over-reliance on the keystone can blind you to when the lens should lead."
          ],
          "prescriptions": [
            "Schedule lens-expression time weekly or biweekly.",
            "Ask: 'What would my lens voice say here?' before finalizing decisions.",
            "Create one lens-honoring ritual that's non-negotiable."
          ]
        }
      },
      "SIGNATURE_ACCENT": {
        "name": "Signature & Accent",
        "ratio": "~90/10",
        "description": "Strong single-voice signature with a subtle accent coloring.",
        "adds": {
          "strengths": [
            "Strong identity: you know exactly who you are.",
            "Efficiency: decisions align with one clear value system.",
            "Accent subtlety: the 10% adds texture without complication."
          ],
          "watchouts": [
            "Accent dismissal: the minor voice may be treated as 'not really me.'",
            "Blind spots: the accent often holds wisdom the signature ignores."
          ],
          "prescriptions": [
            "Monthly check-in: 'What is my accent voice trying to tell me?'",
            "Notice when the accent voice surfaces—it's usually important."
          ]
        }
      },
      "PURELINE": {
        "name": "Pureline",
        "ratio": "~95/5+",
        "description": "Near-pure single-voice orientation with trace coloring.",
        "adds": {
          "strengths": [
            "Extreme clarity: your identity is unmistakable.",
            "Focus: no internal negotiation required.",
            "Depth: you've likely developed this voice thoroughly."
          ],
          "watchouts": [
            "Shadow blindness: the 5% often holds suppressed material.",
            "Inflexibility: situations requiring the trace voice may feel alien.",
            "Over-identification: you may resist acknowledging the trace exists."
          ],
          "prescriptions": [
            "Acknowledge the trace voice exists, even if it rarely leads.",
            "When stuck, ask: 'What would my 5% suggest?'"
          ]
        }
      }
    },
    "trio_modes": {
      "TRI_HELIX": {
        "name": "Tri-Helix",
        "ratio": "~33/33/33",
        "description": "Three voices in balanced rotation. Context-dependent expression.",
        "adds": {
          "strengths": [
            "Maximum versatility: you have three distinct modes available.",
            "Resilience: if one voice is blocked, two others remain.",
            "Depth: triple-perspective on every situation."
          ],
          "watchouts": [
            "Decision paralysis: three voices can debate indefinitely.",
            "Identity diffusion: 'Who am I really?' intensifies.",
            "Energy cost: maintaining three active modes is demanding."
          ],
          "prescriptions": [
            "Assign situations to voices: 'Work = Voice A, Home = Voice B, Creative = Voice C.'",
            "Use time-boxing: let each voice have dedicated expression windows."
          ]
        }
      },
      "KEYSTONE_PRISM": {
        "name": "Keystone Prism",
        "ratio": "~50/25/25",
        "description": "One keystone anchor with two equal lenses refracting it.",
        "adds": {
          "strengths": [
            "Anchored flexibility: clear center with dual coloring.",
            "Rich expression: two lenses create prismatic depth.",
            "Stability: the keystone provides consistent ground."
          ],
          "watchouts": [
            "Lens competition: the two secondary voices may conflict.",
            "Keystone over-reliance: the lenses may feel like decorations."
          ],
          "prescriptions": [
            "Notice which lens is active; name it before proceeding.",
            "Create separate rituals for each lens voice."
          ]
        }
      },
      "KEYSTONE_ORBIT": {
        "name": "Keystone Orbit",
        "ratio": "~60/25/15",
        "description": "Clear hierarchy: keystone leads, lens shapes, shadow observes.",
        "adds": {
          "strengths": [
            "Clear command structure: keystone decides, lens advises, shadow watches.",
            "Shadow wisdom: the 15% often holds unconventional insights.",
            "Efficiency: less internal debate than balanced triads."
          ],
          "watchouts": [
            "Shadow suppression: the 15% may be ignored until it erupts.",
            "Hierarchy rigidity: sometimes the shadow should lead."
          ],
          "prescriptions": [
            "Check in with the shadow voice monthly.",
            "In crisis, deliberately ask: 'What does my shadow see?'"
          ]
        }
      },
      "TRIAD_STACK": {
        "name": "Triad Stack",
        "ratio": "variable",
        "description": "Three active voices without a clean geometric pattern.",
        "adds": {
          "strengths": [
            "Unique configuration: your blend doesn't fit neat boxes.",
            "Adaptability: no preset hierarchy to follow."
          ],
          "watchouts": [
            "Unpredictability: harder to explain your patterns to others.",
            "Integration challenge: finding coherence requires more work."
          ],
          "prescriptions": [
            "Map your specific ratios and name your stack.",
            "Create personal rules for which voice leads when."
          ]
        }
      }
    },
    "polyphonic_modes": {
      "CHORD_TOP4": {
        "name": "Chord (Top-4)",
        "description": "Four meaningful voices in structured harmony.",
        "adds": {
          "strengths": [
            "Rich harmony: four-part chord creates complex expression.",
            "Flexibility: many configurations available."
          ],
          "watchouts": [
            "Complexity: harder to maintain coherent identity.",
            "Decision overhead: four voices voting takes time."
          ],
          "prescriptions": [
            "Identify your 'first among equals' for tie-breaking.",
            "Simplify when overwhelmed: pick two voices for the current context."
          ]
        }
      },
      "CHORD_TOP_HEAVY": {
        "name": "Chord (Top-Heavy)",
        "description": "Strong top three with a meaningful fourth presence.",
        "adds": {
          "strengths": [
            "Near-triad clarity with extra depth.",
            "Fourth voice provides backup perspective."
          ],
          "watchouts": [
            "Fourth voice neglect: may be treated as noise."
          ],
          "prescriptions": [
            "Check what the fourth voice adds before dismissing it."
          ]
        }
      },
      "CHORUS_DISTRIBUTED": {
        "name": "Chorus (Distributed)",
        "description": "Many voices active with similar weights.",
        "adds": {
          "strengths": [
            "Ultimate flexibility: you can be many things.",
            "Empathy: you understand many perspectives from inside."
          ],
          "watchouts": [
            "Identity fog: 'What do I actually want?' is chronically unclear.",
            "Decision paralysis: no clear tiebreaker.",
            "Energy diffusion: maintaining many modes is exhausting."
          ],
          "prescriptions": [
            "Create external structures to impose clarity.",
            "For big decisions, artificially narrow to top 2-3 voices.",
            "Embrace being a 'chorus person' rather than fighting it."
          ]
        }
      },
      "CHORUS_CONTEXT_SPLIT": {
        "name": "Chorus (Context-Split)",
        "description": "Different anchors emerge in different contexts.",
        "adds": {
          "strengths": [
            "Contextual mastery: you become what each situation needs.",
            "Compartmentalization: clear mode switches."
          ],
          "watchouts": [
            "Fragmentation: contexts may feel like different people.",
            "Transition strain: switching modes takes energy."
          ],
          "prescriptions": [
            "Map your context-voice associations explicitly.",
            "Create transition rituals between contexts."
          ]
        }
      }
    }
  },
  "rules": {
    "version": "HPMA-Rules-1.0",
    "thresholds": {
      "very_high": 7,
      "high": 6,
      "moderate_high": 5.5,
      "moderate": 4.5,
      "moderate_low": 3.5,
      "low": 3,
      "very_low": 2
    },
    "rules": [
      {
        "id": "high_openness",
        "when": "scores.hexaco.O >= thresholds.high",
        "add_flags": [
          "HIGH_OPENNESS"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Your high Openness amplifies exploration and creative synthesis."
          ],
          "career.notes": [
            "Seek roles where novelty and learning are core to the work."
          ]
        }
      },
      {
        "id": "low_openness",
        "when": "scores.hexaco.O <= thresholds.low",
        "add_flags": [
          "LOW_OPENNESS"
        ],
        "add_snippets": {
          "strengths.notes": [
            "You prefer proven approaches over constant experimentation."
          ],
          "career.notes": [
            "Environments with clear procedures may feel more comfortable."
          ]
        }
      },
      {
        "id": "high_conscientiousness",
        "when": "scores.hexaco.C >= thresholds.high",
        "add_flags": [
          "HIGH_C"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Strong conscientiousness provides natural execution discipline."
          ],
          "self_improvement.notes": [
            "Your follow-through is a strength; avoid over-planning."
          ]
        }
      },
      {
        "id": "low_conscientiousness",
        "when": "scores.hexaco.C <= thresholds.low",
        "add_flags": [
          "LOW_C"
        ],
        "add_snippets": {
          "watchouts.notes": [
            "Execution may require external scaffolding (deadlines, accountability partners)."
          ],
          "self_improvement.notes": [
            "Use time-boxing and commitment devices to bridge the idea-action gap."
          ]
        }
      },
      {
        "id": "high_extraversion",
        "when": "scores.hexaco.X >= thresholds.high",
        "add_flags": [
          "HIGH_X"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Social energy is abundant; remember others may need more quiet time."
          ],
          "career.notes": [
            "Collaborative, high-interaction roles likely energize you."
          ]
        }
      },
      {
        "id": "low_extraversion",
        "when": "scores.hexaco.X <= thresholds.low",
        "add_flags": [
          "LOW_X",
          "INTROVERT"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Social time costs energy; schedule recharge time explicitly."
          ],
          "career.notes": [
            "Deep-work environments with limited meetings may suit you better."
          ]
        }
      },
      {
        "id": "high_agreeableness",
        "when": "scores.hexaco.A >= thresholds.high",
        "add_flags": [
          "HIGH_A"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Natural warmth makes connection easy; watch for over-accommodation."
          ],
          "watchouts.notes": [
            "Your agreeableness is a strength, but boundaries matter too."
          ]
        }
      },
      {
        "id": "low_agreeableness",
        "when": "scores.hexaco.A <= thresholds.low",
        "add_flags": [
          "LOW_A"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Directness can be efficient but may occasionally feel abrasive to others."
          ],
          "career.notes": [
            "Roles requiring tough decisions without consensus may fit well."
          ]
        }
      },
      {
        "id": "high_emotionality",
        "when": "scores.hexaco.E >= thresholds.high",
        "add_flags": [
          "HIGH_E"
        ],
        "add_snippets": {
          "relationships.notes": [
            "High emotional sensitivity means deeper connections but also more vulnerability."
          ],
          "self_improvement.notes": [
            "Emotional regulation practices may be especially valuable."
          ]
        }
      },
      {
        "id": "low_emotionality",
        "when": "scores.hexaco.E <= thresholds.low",
        "add_flags": [
          "LOW_E"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Emotional stability under pressure is a resilience asset."
          ],
          "relationships.notes": [
            "Others may need more emotional acknowledgment than you naturally offer."
          ]
        }
      },
      {
        "id": "high_honesty_humility",
        "when": "scores.hexaco.H >= thresholds.high",
        "add_flags": [
          "HIGH_H"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Integrity and authenticity are core values you naturally embody."
          ],
          "career.notes": [
            "Environments with ethical alignment matter more to you than to most."
          ]
        }
      },
      {
        "id": "low_honesty_humility",
        "when": "scores.hexaco.H <= thresholds.low",
        "add_flags": [
          "LOW_H"
        ],
        "add_snippets": {
          "watchouts.notes": [
            "Status and self-interest may drive decisions more than you consciously recognize."
          ]
        }
      },
      {
        "id": "high_autonomy",
        "when": "scores.motives.autonomy >= thresholds.high",
        "add_flags": [
          "HIGH_AUTONOMY"
        ],
        "add_snippets": {
          "career.notes": [
            "Autonomy is non-negotiable; hierarchical control will feel corrosive."
          ],
          "money.notes": [
            "Financial decisions often optimize for freedom over accumulation."
          ]
        }
      },
      {
        "id": "low_autonomy",
        "when": "scores.motives.autonomy <= thresholds.low",
        "add_flags": [
          "LOW_AUTONOMY"
        ],
        "add_snippets": {
          "career.notes": [
            "Structure and guidance can feel supportive rather than constraining."
          ]
        }
      },
      {
        "id": "high_security",
        "when": "scores.motives.security >= thresholds.high",
        "add_flags": [
          "HIGH_SECURITY"
        ],
        "add_snippets": {
          "money.notes": [
            "Financial safety margins matter; don't let others rush risky decisions."
          ],
          "career.notes": [
            "Stability in employment matters more than average."
          ]
        }
      },
      {
        "id": "low_security",
        "when": "scores.motives.security <= thresholds.very_low",
        "add_flags": [
          "LOW_SECURITY"
        ],
        "add_snippets": {
          "money.notes": [
            "Risk tolerance is higher than average; others may see this as reckless."
          ],
          "self_improvement.notes": [
            "Some contingency planning may be wise even if it doesn't feel urgent."
          ]
        }
      },
      {
        "id": "high_belonging",
        "when": "scores.motives.belonging >= thresholds.high",
        "add_flags": [
          "HIGH_BELONGING"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Belonging is a core need; isolation can feel existentially threatening."
          ],
          "career.notes": [
            "Team cohesion and workplace community matter deeply."
          ]
        }
      },
      {
        "id": "low_belonging",
        "when": "scores.motives.belonging <= thresholds.low",
        "add_flags": [
          "LOW_BELONGING"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Independence is natural; watch for isolation creep."
          ],
          "career.notes": [
            "Remote work and solo contributions may fit well."
          ]
        }
      },
      {
        "id": "high_status",
        "when": "scores.motives.status >= thresholds.high",
        "add_flags": [
          "HIGH_STATUS"
        ],
        "add_snippets": {
          "career.notes": [
            "Recognition and advancement are meaningful motivators."
          ],
          "money.notes": [
            "Status symbols may hold genuine value for you."
          ]
        }
      },
      {
        "id": "low_status",
        "when": "scores.motives.status <= thresholds.very_low",
        "add_flags": [
          "LOW_STATUS"
        ],
        "add_snippets": {
          "money.notes": [
            "Status isn't a driver; you may undervalue market rates or titles."
          ],
          "career.notes": [
            "You won't play status games naturally; this can be freeing or career-limiting."
          ]
        }
      },
      {
        "id": "high_mastery",
        "when": "scores.motives.mastery >= thresholds.high",
        "add_flags": [
          "HIGH_MASTERY"
        ],
        "add_snippets": {
          "career.notes": [
            "Skill development and competence are intrinsically rewarding."
          ],
          "self_improvement.notes": [
            "Learning is self-motivating; no external push required."
          ]
        }
      },
      {
        "id": "low_mastery",
        "when": "scores.motives.mastery <= thresholds.low",
        "add_flags": [
          "LOW_MASTERY"
        ],
        "add_snippets": {
          "career.notes": [
            "Skill-building may need external structure or incentives."
          ]
        }
      },
      {
        "id": "high_purpose",
        "when": "scores.motives.purpose >= thresholds.high",
        "add_flags": [
          "HIGH_PURPOSE"
        ],
        "add_snippets": {
          "career.notes": [
            "Meaning-alignment with work is non-negotiable; paycheck alone won't sustain you."
          ],
          "self_improvement.notes": [
            "Connect all efforts to 'why' or motivation fades."
          ]
        }
      },
      {
        "id": "low_purpose",
        "when": "scores.motives.purpose <= thresholds.low",
        "add_flags": [
          "LOW_PURPOSE"
        ],
        "add_snippets": {
          "self_improvement.notes": [
            "Existential questions may feel irrelevant; practical outcomes matter more."
          ]
        }
      },
      {
        "id": "high_seeking",
        "when": "scores.affects.seeking >= thresholds.high",
        "add_flags": [
          "HIGH_SEEKING"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Curiosity and exploration drive are natural fuel."
          ],
          "watchouts.notes": [
            "Novelty-seeking can scatter attention; channel it deliberately."
          ]
        }
      },
      {
        "id": "high_fear",
        "when": "scores.affects.fear >= thresholds.high",
        "add_flags": [
          "HIGH_FEAR"
        ],
        "add_snippets": {
          "watchouts.notes": [
            "Anxiety may block action; distinguish real threats from false alarms."
          ],
          "self_improvement.notes": [
            "Exposure practices and anxiety management skills may be high-leverage."
          ]
        }
      },
      {
        "id": "low_fear",
        "when": "scores.affects.fear <= thresholds.low",
        "add_flags": [
          "LOW_FEAR"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Low anxiety enables calm under pressure."
          ],
          "watchouts.notes": [
            "May underestimate genuine risks; seek external risk-checking."
          ]
        }
      },
      {
        "id": "high_care",
        "when": "scores.affects.care >= thresholds.high",
        "add_flags": [
          "HIGH_CARE"
        ],
        "add_snippets": {
          "relationships.notes": [
            "Nurturing instincts are strong; be mindful of over-giving."
          ],
          "parenting.notes": [
            "Natural caretaking strengths; watch for burnout from over-extending."
          ]
        }
      },
      {
        "id": "high_play",
        "when": "scores.affects.play >= thresholds.high",
        "add_flags": [
          "HIGH_PLAY"
        ],
        "add_snippets": {
          "hobbies.notes": [
            "Playfulness is a wellspring; protect leisure from productivity guilt."
          ],
          "relationships.notes": [
            "Lightheartedness can ease tension and build connection."
          ]
        }
      },
      {
        "id": "low_play",
        "when": "scores.affects.play <= thresholds.low",
        "add_flags": [
          "LOW_PLAY"
        ],
        "add_snippets": {
          "hobbies.notes": [
            "Schedule unstructured play deliberately; it won't happen naturally."
          ],
          "self_improvement.notes": [
            "Seriousness is useful but unrelenting; find outlets for levity."
          ]
        }
      },
      {
        "id": "explorer_amplified",
        "when": "scores.hexaco.O >= thresholds.high AND scores.affects.seeking >= thresholds.high AND scores.motives.autonomy >= thresholds.moderate_high",
        "add_flags": [
          "EXPLORER_AMPLIFIED"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Triple-reinforced exploration drive: Openness + Seeking + Autonomy form a powerful discovery engine."
          ]
        }
      },
      {
        "id": "philosopher_amplified",
        "when": "scores.motives.purpose >= thresholds.high AND scores.hexaco.O >= thresholds.moderate_high",
        "add_flags": [
          "PHILOSOPHER_AMPLIFIED"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Meaning-seeking is a core identity marker, not just a preference."
          ]
        }
      },
      {
        "id": "protector_amplified",
        "when": "scores.motives.security >= thresholds.high AND scores.affects.fear >= thresholds.moderate_high",
        "add_flags": [
          "PROTECTOR_AMPLIFIED"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Vigilance is finely tuned; you catch threats others miss."
          ],
          "watchouts.notes": [
            "Hypervigilance can tip into chronic worry; calibrate threat perception."
          ]
        }
      },
      {
        "id": "connector_amplified",
        "when": "scores.hexaco.A >= thresholds.high AND scores.motives.belonging >= thresholds.high AND scores.affects.care >= thresholds.moderate_high",
        "add_flags": [
          "CONNECTOR_AMPLIFIED"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Relational attunement is a superpower; you build bridges instinctively."
          ]
        }
      },
      {
        "id": "performer_amplified",
        "when": "scores.hexaco.X >= thresholds.high AND scores.motives.status >= thresholds.moderate_high AND scores.affects.play >= thresholds.moderate_high",
        "add_flags": [
          "PERFORMER_AMPLIFIED"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Charisma and presence come naturally; others gravitate toward your energy."
          ]
        }
      },
      {
        "id": "organizer_amplified",
        "when": "scores.hexaco.C >= thresholds.high AND scores.motives.mastery >= thresholds.high",
        "add_flags": [
          "ORGANIZER_AMPLIFIED"
        ],
        "add_snippets": {
          "strengths.notes": [
            "Structure and excellence drive reinforce each other; you build things that last."
          ]
        }
      },
      {
        "id": "autonomy_belonging_tension",
        "when": "scores.motives.autonomy >= thresholds.high AND scores.motives.belonging >= thresholds.high",
        "add_flags": [
          "AUTONOMY_BELONGING_TENSION"
        ],
        "add_snippets": {
          "relationships.notes": [
            "You want both independence and deep connection—this is a legitimate tension, not a flaw."
          ],
          "self_improvement.notes": [
            "Negotiate explicit 'together time' and 'alone time' rather than hoping both happen naturally."
          ]
        }
      },
      {
        "id": "security_seeking_tension",
        "when": "scores.motives.security >= thresholds.high AND scores.affects.seeking >= thresholds.high",
        "add_flags": [
          "SECURITY_SEEKING_TENSION"
        ],
        "add_snippets": {
          "watchouts.notes": [
            "You want both safety and novelty—these can coexist through 'safe exploration' patterns."
          ],
          "self_improvement.notes": [
            "Bounded experiments (time-boxed, reversible) let you explore without triggering security alarms."
          ]
        }
      },
      {
        "id": "mastery_play_tension",
        "when": "scores.motives.mastery >= thresholds.high AND scores.affects.play >= thresholds.high",
        "add_flags": [
          "MASTERY_PLAY_TENSION"
        ],
        "add_snippets": {
          "hobbies.notes": [
            "You may turn hobbies into skill-building projects—sometimes let play just be play."
          ]
        }
      },
      {
        "id": "validity_idealized",
        "when": "validity.idealized == true",
        "add_flags": [
          "VALIDITY_WARNING"
        ],
        "add_snippets": {
          "validity.notes": [
            "Some responses appear idealized. Results may reflect aspirations more than current patterns."
          ]
        }
      },
      {
        "id": "validity_random",
        "when": "validity.random == true",
        "add_flags": [
          "VALIDITY_WARNING"
        ],
        "add_snippets": {
          "validity.notes": [
            "Response patterns appear inconsistent. Consider retaking with focused attention."
          ]
        }
      },
      {
        "id": "validity_inattentive",
        "when": "validity.inattentive == true",
        "add_flags": [
          "VALIDITY_WARNING"
        ],
        "add_snippets": {
          "validity.notes": [
            "Attention check items were missed. Results may be less reliable."
          ]
        }
      },
      {
        "id": "twin_helix_integration",
        "when": "roster.duet.mode == 'TWIN_HELIX'",
        "add_flags": [
          "BALANCED_DUET"
        ],
        "add_snippets": {
          "self_improvement.notes": [
            "With two balanced voices, explicitly name which is leading before major decisions."
          ]
        }
      },
      {
        "id": "pureline_shadow_work",
        "when": "roster.duet.mode == 'PURELINE' OR roster.duet.mode == 'SIGNATURE_ACCENT'",
        "add_flags": [
          "DOMINANT_VOICE"
        ],
        "add_snippets": {
          "self_improvement.notes": [
            "Your secondary voice is quiet but not absent; check in with it monthly."
          ]
        }
      },
      {
        "id": "tri_helix_complexity",
        "when": "roster.trio.mode == 'TRI_HELIX'",
        "add_flags": [
          "BALANCED_TRIO"
        ],
        "add_snippets": {
          "self_improvement.notes": [
            "Three balanced voices means more internal negotiation; use context-based switching rules."
          ]
        }
      },
      {
        "id": "chorus_integration",
        "when": "roster.structure == 'CHORUS' OR roster.structure == 'CHORD'",
        "add_flags": [
          "POLYPHONIC"
        ],
        "add_snippets": {
          "self_improvement.notes": [
            "Your profile is genuinely complex; embrace it rather than forcing simplicity."
          ],
          "watchouts.notes": [
            "Decision paralysis may come from too many internal voices; narrow to 2-3 for any given choice."
          ]
        }
      }
    ]
  },
  "dyads": {
    "version": "HPMA-Evals-Dyads-1.0",
    "SEEKER_SAGE": {
      "tagline": "Discovery plus meaning. Curiosity with a compass.",
      "domains": {
        "strengths": {
          "bullets": [
            "Synthesis: connects disparate ideas into new frameworks.",
            "Truth-seeking: prefers coherence and evidence over vibes and tradition.",
            "Exploration drive: energized by possibility, learning, and uncharted territory.",
            "Depth: willing to go further than most to understand something fully.",
            "Value-driven: pursues meaning, not just novelty for its own sake."
          ],
          "evidence_hints": [
            {
              "when": "traits.O >= 6.0 and affect.seeking >= 6.0",
              "because": "High Openness + high Seeking supports exploration/synthesis capacity."
            },
            {
              "when": "motives.purpose >= 6.0",
              "because": "High Purpose drive ensures exploration serves meaning, not distraction."
            }
          ]
        },
        "watchouts": {
          "bullets": [
            "Infinite runway: more theories than shipping cycles.",
            "Overthinking: decisions delayed by the desire for 'the clean model.'",
            "Abstraction bias: may intellectualize emotions rather than feeling them.",
            "Perfectionism: the search for the 'right' answer can block good-enough action.",
            "Isolation risk: deep work preferences can reduce connection time."
          ],
          "telltales": [
            "You keep refining the plan after the plan is already sufficient.",
            "You explain your feelings rather than expressing them.",
            "You've researched a decision extensively but still haven't acted."
          ]
        },
        "career": {
          "best_environments": [
            "Autonomy + deep work time + intellectual challenge.",
            "Problem spaces where 'unknown unknowns' are normal.",
            "Organizations that value thinking and meaning, not just output metrics.",
            "Roles with exploration phases built into the job."
          ],
          "role_patterns": [
            "Research → prototype → narrative → repeat.",
            "Strategy + invention roles (not pure maintenance or operations).",
            "Teaching, writing, advising, consulting, R&D."
          ],
          "anti_patterns": [
            "Status games and constant performance metrics.",
            "Highly bureaucratic environments with rigid processes.",
            "Roles requiring constant social performance without depth.",
            "Pure execution work with no creative or strategic latitude."
          ],
          "collaboration": [
            "Pairs well with builders who like finishing what you start.",
            "Works well with connectors who can translate your ideas for broader audiences.",
            "May frustrate pure doers who want action without theory."
          ]
        },
        "money": {
          "style": [
            "Spends on learning/tools/experiments more than status symbols.",
            "Values time and freedom over luxury goods.",
            "May accumulate resources as 'optionality' rather than spending."
          ],
          "risks": [
            "Tool/course accumulation without shipping.",
            "Delayed financial action while 'researching the best approach.'",
            "May undervalue market rates because status isn't a driver."
          ],
          "guardrails": [
            "Ship-to-spend rule: new learning spend unlocks after deliverables ship.",
            "Set financial review dates to prevent indefinite research phases.",
            "Automate savings/investing to bypass analysis paralysis."
          ]
        },
        "relationships": {
          "offers": [
            "Depth, curiosity, meaningful conversation.",
            "Loyal partnership once committed.",
            "Intellectual companionship and growth orientation.",
            "Values-driven consistency."
          ],
          "needs": [
            "Freedom + intellectual intimacy + shared purpose.",
            "Space for solitude and deep work.",
            "A partner who respects your inner world."
          ],
          "triggers": [
            "Control, shallow status games, dismissal of values.",
            "Being rushed to decide without time to think.",
            "Pressure to perform socially when you need to recharge."
          ],
          "repair": [
            "Name the value conflict explicitly, then pick a concrete behavior change.",
            "Don't over-explain; sometimes presence is the repair.",
            "Acknowledge when you've intellectualized instead of connected."
          ]
        },
        "parenting": {
          "strengths": [
            "Models curiosity and principled thinking.",
            "Creates learning-rich environments.",
            "Takes children's questions seriously.",
            "Teaches frameworks for understanding the world."
          ],
          "traps": [
            "Over-explaining when the child needs presence first.",
            "Turning every moment into a teaching opportunity.",
            "Expecting adult-level reasoning from children."
          ],
          "do_more": [
            "Short rituals and consistency scaffolds.",
            "Physical play and non-verbal connection.",
            "Being present without agenda."
          ],
          "do_less": [
            "Turning every moment into a philosophy seminar.",
            "Analyzing the child's behavior instead of just being with them."
          ]
        },
        "hobbies": {
          "recharge": [
            "Reading, building, tinkering, long walks with big questions.",
            "Solitary activities that allow the mind to wander.",
            "Nature, especially novel environments."
          ],
          "play": [
            "Skill games, puzzles, creative tools, exploration trips.",
            "Learning new domains for fun.",
            "Building things (physical or digital)."
          ],
          "warning_signs": [
            "Hobbies becoming another 'project' with metrics.",
            "Guilt about unproductive leisure."
          ]
        },
        "self_improvement": {
          "leverage": [
            "Timebox exploration; define 'done' early and commit to it.",
            "Use external scaffolds that don't feel like cages.",
            "Ship before it's perfect; iterate publicly."
          ],
          "keystone_constraints": [
            "One active 'big exploration' at a time.",
            "Finish before starting the next thing."
          ],
          "if_then_rules": [
            "If I'm still researching after 3 sessions, then I must prototype the smallest test.",
            "If I've explained my plan to 2 people, then I must act this week.",
            "If I notice myself over-theorizing, then I stop and do one concrete thing."
          ],
          "growth_edges": [
            "Practice shipping imperfect work.",
            "Develop comfort with ambiguity in relationships.",
            "Build embodied practices (movement, sensation) to balance intellectual ones."
          ]
        },
        "compatibility": {
          "complimentary": [
            {
              "match": "VISIONARY_BUILDER",
              "why": "Builder energy helps ideas ship; shared exploration base."
            },
            {
              "match": "BRIDGE_SCHOLAR",
              "why": "Depth + warmth; shared meaning orientation."
            },
            {
              "match": "SYSTEMS_THEORIST",
              "why": "Both value coherent models; can co-create frameworks."
            }
          ],
          "friction": [
            {
              "match": "WATCHFUL_CHAMPION",
              "why": "Control vs freedom + tone mismatch; values may conflict."
            },
            {
              "match": "SHOWRUNNER_EXECUTIVE",
              "why": "May feel too metrics-driven or performative."
            }
          ],
          "conflict": [
            {
              "match": "High-Status Performer profiles",
              "why": "Meaning-first vs applause-first value war; fundamentally different currencies."
            }
          ],
          "general_notes": [
            "You need intellectual respect; partners who dismiss your ideas will feel corrosive.",
            "High belonging partners may want more togetherness than you naturally offer.",
            "You may need to explicitly schedule connection time."
          ]
        }
      }
    },
    "VISIONARY_BUILDER": {
      "tagline": "Ideas that ship. Exploration meets execution.",
      "domains": {
        "strengths": {
          "bullets": [
            "Idea-to-execution bridge: can both envision and build.",
            "Practical creativity: innovations that actually work.",
            "Progress-oriented: energized by seeing ideas become real.",
            "Adaptive planning: explores options then commits to action."
          ]
        },
        "watchouts": {
          "bullets": [
            "Scope creep: keeps adding features before shipping.",
            "Torn between exploring more vs finishing current work.",
            "May abandon projects for shinier ideas."
          ]
        },
        "career": {
          "best_environments": [
            "Startups, R&D labs, product development roles.",
            "Environments that reward both innovation and execution."
          ],
          "role_patterns": [
            "Product manager, founder, inventor, entrepreneur."
          ],
          "anti_patterns": [
            "Pure research with no shipping expectation.",
            "Pure operations with no innovation latitude."
          ]
        },
        "money": {
          "style": [
            "Invests in tools and capabilities.",
            "May bootstrap ventures rather than pure consumption."
          ]
        },
        "relationships": {
          "offers": [
            "Growth partnership, shared projects."
          ],
          "needs": [
            "Space to work on ideas + appreciation for outputs."
          ]
        },
        "self_improvement": {
          "leverage": [
            "Commit to shipping timelines before exploring.",
            "Use explore-exploit cycles explicitly."
          ]
        }
      }
    },
    "BRIDGE_SCHOLAR": {
      "tagline": "Depth plus warmth. Ideas as bridges.",
      "domains": {
        "strengths": {
          "bullets": [
            "Translates complex ideas into relatable terms.",
            "Builds intellectual communities.",
            "Mentors and teaches naturally.",
            "Combines rigor with emotional intelligence."
          ]
        },
        "watchouts": {
          "bullets": [
            "May over-prioritize harmony over truth.",
            "Difficulty with conflict or critique.",
            "Can lose self in others' needs."
          ]
        },
        "career": {
          "best_environments": [
            "Teaching, coaching, facilitation, therapy.",
            "Research with collaborative elements."
          ],
          "role_patterns": [
            "Professor, counselor, community builder."
          ]
        },
        "relationships": {
          "offers": [
            "Deep understanding, patient listening, wisdom."
          ],
          "needs": [
            "Intellectual stimulation + emotional closeness."
          ]
        }
      }
    },
    "SYSTEMS_THEORIST": {
      "tagline": "Models that work. Theory meets practice.",
      "domains": {
        "strengths": {
          "bullets": [
            "Builds coherent systems from complexity.",
            "Long-term strategic thinking.",
            "Values efficiency and elegance.",
            "Can explain 'why' behind processes."
          ]
        },
        "watchouts": {
          "bullets": [
            "May over-optimize for elegance vs real-world messiness.",
            "Can be rigid about 'the right way.'",
            "May dismiss emotional factors as noise."
          ]
        },
        "career": {
          "best_environments": [
            "Strategy consulting, systems architecture, policy.",
            "Roles requiring both analysis and implementation."
          ]
        },
        "relationships": {
          "offers": [
            "Stability, clear thinking, long-term planning."
          ],
          "needs": [
            "Respect for intellect + space for deep work."
          ]
        }
      }
    },
    "WAYFINDER_DIPLOMAT": {
      "tagline": "New paths, new friends. Adventure as connection.",
      "domains": {
        "strengths": {
          "bullets": [
            "Makes friends anywhere.",
            "Opens doors through genuine curiosity about people."
          ]
        }
      }
    },
    "SENTINEL_SCOUT": {
      "tagline": "Careful curiosity. Exploration with eyes open.",
      "domains": {
        "strengths": {
          "bullets": [
            "Risk-aware exploration.",
            "Preparation meets adventure."
          ]
        }
      }
    },
    "SPOTLIGHT_PIONEER": {
      "tagline": "First on stage, first on the trail. Bold and visible.",
      "domains": {
        "strengths": {
          "bullets": [
            "Charismatic innovation.",
            "Makes new things exciting for others."
          ]
        }
      }
    },
    "VIGILANT_STOIC": {
      "tagline": "Prepared wisdom. Meaning under pressure.",
      "domains": {
        "strengths": {
          "bullets": [
            "Calm in crisis.",
            "Values-driven resilience."
          ]
        }
      }
    },
    "PUBLIC_INTELLECTUAL": {
      "tagline": "Ideas on stage. Thought leadership.",
      "domains": {
        "strengths": {
          "bullets": [
            "Communicates complex ideas compellingly.",
            "Builds audiences around meaning."
          ]
        }
      }
    },
    "COMMUNITY_OPERATOR": {
      "tagline": "Systems for people. Structure that serves.",
      "domains": {
        "strengths": {
          "bullets": [
            "Builds organizations that care.",
            "Process + warmth combined."
          ]
        }
      }
    },
    "RISK_STEWARD": {
      "tagline": "Managed uncertainty. Plans with backup plans.",
      "domains": {
        "strengths": {
          "bullets": [
            "Excellent contingency planning.",
            "Brings order to chaos without killing flexibility."
          ]
        }
      }
    },
    "SHOWRUNNER_EXECUTIVE": {
      "tagline": "Productions that deliver. Leadership with flair.",
      "domains": {
        "strengths": {
          "bullets": [
            "Gets things done with style.",
            "Motivates teams toward visible results."
          ]
        }
      }
    },
    "GUARDIAN_CARETAKER": {
      "tagline": "Safety through belonging. Protection as love.",
      "domains": {
        "strengths": {
          "bullets": [
            "Creates emotionally safe spaces.",
            "Nurturing + protective instincts."
          ]
        }
      }
    },
    "CHARISMATIC_HOST": {
      "tagline": "Everyone belongs. Energy that includes.",
      "domains": {
        "strengths": {
          "bullets": [
            "Makes everyone feel welcome.",
            "High social energy + genuine care."
          ]
        }
      }
    },
    "WATCHFUL_CHAMPION": {
      "tagline": "Visible strength. Protection with presence.",
      "domains": {
        "strengths": {
          "bullets": [
            "Commands attention while keeping watch.",
            "Protective leadership."
          ]
        }
      }
    }
  }
} as ContentBundle;
