/**
 * Build script: Converts YAML content files to a single TypeScript module.
 * Run with: npx tsx scripts/generate-content.ts
 */

import * as yaml from 'js-yaml';
import * as fs from 'fs';
import * as path from 'path';

const CONTENT_DIR = path.join(process.cwd(), 'content');
const OUTPUT_FILE = path.join(process.cwd(), 'lib/fieldguide/content-bundle.ts');

function loadYaml<T>(filename: string): T {
  const filePath = path.join(CONTENT_DIR, filename);
  const content = fs.readFileSync(filePath, 'utf8');
  return yaml.load(content) as T;
}

function generateContentBundle() {
  console.log('Loading YAML content files...');

  const vocab = loadYaml('vocab.yml');
  const identities = loadYaml('identities.yml');
  const modes = loadYaml('modes.yml');
  const rules = loadYaml('rules.yml');
  const dyads = loadYaml('evaluations/dyads.yml');
  const primaries = loadYaml('evaluations/primaries.yml');

  const bundle = {
    vocab,
    identities,
    modes,
    rules,
    dyads,
    primaries,
  };

  console.log('Generating TypeScript module...');

  const output = `// Auto-generated by scripts/generate-content.ts
// Do not edit manually - edit YAML files in /content instead

import { ContentBundle } from './types';

export const contentBundle: ContentBundle = ${JSON.stringify(bundle, null, 2)} as ContentBundle;
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✓ Generated ${OUTPUT_FILE}`);
}

generateContentBundle();
